apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devopslab9.fullname" . }}
  labels:
    {{- include "devopslab9.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  serviceName: {{ include "devopslab9.fullname" . }}
  podManagementPolicy: "Parallel"
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devopslab9.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devopslab9.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devopslab9.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: FILEPATH
              value: {{ .Values.envs.filepath }}
          volumeMounts:
            - name: {{ .Values.volumeClaim.name }}
              mountPath: {{ .Values.volumeClaim.mountPath }}
            - name: {{ .Values.initVolume.name }}
              mountPath: {{ .Values.initVolume.mountPath }}
      initContainers:
          - name: install
            image: busybox
            command:
            - wget
            - "-O"
            - "/app/html/index.html"
            - http://info.cern.ch
            volumeMounts:
            - name: {{ .Values.initVolume.name }}
              mountPath: "/app/html/"
      volumes:
        - name: {{ .Values.initVolume.name }}
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.volumeClaim.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.volumeClaim.storage }}