version: "3"

networks:
  dashboard:

services:
  web_app:
    image: totenhund/devops_lab:latest
    container_name: web_app
    ports:
      - "5000:5000"
    networks:
      - dashboard
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 256M


  grafana_ui:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - dashboard
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 256M


  loki_logging:
    image: grafana/loki:2.3.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - dashboard
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 256M

  promtail:
    image: grafana/promtail:2.3.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - dashboard
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 256M

  prometheus_metrics:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dashboard
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 256M