pipeline {

    environment {
        APP_PATH = 'python_app'
        CODE = 'app.py'
        TESTS = 'tests'
        registry = "totenhund/devops_lab"
        registryCredential = 'docker_id'
        dockerImage = ''
    }
    agent {
        dockerfile {
            dir 'jenkins'
            args '-u root -v $HOME/.cache:/root/.cache -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('deps') {
            steps {
                dir("${APP_PATH}") {
                    sh 'pip3 install -r python_app/requirements.txt'
                }
            }
        }
        stage('tests') {
            steps {
                parallel (
                    'codestyle': {
                        dir("${APP_PATH}") {
                            sh 'isort ${CODE}'
                        }
                    },

                    'test': {
                        dir("${APP_PATH}") {
                            sh 'pytest ${TESTS}'
                        }
                    }
                )

            }
        }
        stage('Build docker image') {
            steps{
                dir("${APP_PATH}") {
                    script {
                        dockerImage = docker.build registry + ":jenkins-$BUILD_NUMBER"
                    }
                }
            }
        }

        stage('Deploy docker image') {
            steps{
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }
    }

    post {
        cleanup { cleanWs() }
    }
}