name: Flask web app

on:
  push:
    branches:
      - 'main'
      
env:
  APP_PATH: ./python_app  
  TESTS: tests  
  IMAGE_NAME: totenhund/python_app_devops  

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip3 install -r python_app/requirements.txt
      - name: Run tests
        run: pytest
